<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search phone
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["/phone/new", "Create phone"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "phone/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldIdphone" class="col-sm-2 control-label">Idphone</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["idphone", "type" => "number", "class" => "form-control", "id" => "fieldIdphone"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNumber" class="col-sm-2 control-label">Number</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["number", "size" => 30, "class" => "form-control", "id" => "fieldNumber"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNueva" class="col-sm-2 control-label">Nueva</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nueva", "size" => 30, "class" => "form-control", "id" => "fieldNueva"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
